### ISSUE TITLE
Limelight on per-line basis

### ISSUE THREAD

**Issue by sudo-nice** [junegunn/limelight.vim#40]
Thank you for a very helpful plugin. Could you, please, advice me a solution to get only the current line highlighted with limelight? My approaches are all around this config:
```
let g:limelight_bop = '^'
let g:limelight_eop = '$'
```
If the cursor moves *not to the end* of the next/previous line, it works well. Here the example where the cursor moved from the middle of line 1 to the middle of the line 2:
![scr1](http://i.imgur.com/F3sdteX.png)

However if the cursor moves *to the end* of the next/previous line, the next line and the line after next get highlighted both:
![scr2](http://i.imgur.com/Iz5GQ3z.png)

Have I overlooked any simple solution here?

**Comment by franckrasolo** [comment]
In case this helps others, the solution to the above is:
```
let g:limelight_bop='^.*$'
let g:limelight_eop='\n'
```

**Comment by aviloff** [comment]
@franckrasolo great solution but there seems to be a performance hit! any way to optimise? Thanks!

**Comment by amariusz** [comment]
Again, in case this help others, I think @sudo-nice solution was OK but matching pattern '$' at the end of line does not work due to this line:

https://github.com/junegunn/limelight.vim/blob/86aaec1700b27618d33d6182f44691d84d2cb6e5/autoload/limelight.vim#L55

After changing it from `let end = searchpos(eop, 'W')[0]` to `let end = searchpos(eop, 'Wc')[0]` the problem with double line highlighting seems to be gone. 

`c` flag means: 

		'c'	accept a match at the Cursor position

**Comment by amariusz** [comment]
Turned out this solution does not work properly if `g:limelight_paragraph_span` is set value greater then 0 so I've reverted the flag change. Instead I've added moving cursor to the beginning of line (`normal 0`) just before the for loop. 
```
  call setpos('.', pos)
  normal 0
  for _ in range(0, span)
    let end = searchpos(eop, 'W')[0]
  endfor
```

This seems to be working fine with `g:limelight_paragraph_span`

**Comment by kevinlawler** [comment]
@amariusz that solution breaks on single-character lines

    aaaa
    bbbb
    cccc
    a
    b
    c

**Comment by kevinlawler** [comment]
!normal 0 && !c-flag` status quo
    !normal 0 &&  c-flag breaks g:limelight_paragraph_span for non-single lines
     normal 0 && !c-flag breaks single-line highlighting for lines of single char
     normal 0 &&  c-flag breaks g:limelight_paragraph_span for non-single lines

needs a separate fix to not break `g:limelight_paragraph_span != 0`
